// <auto-generated />
using System;
using LineCon.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LineCon.Migrations
{
    [DbContext(typeof(LineConContext))]
    [Migration("20181203002735_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LineCon.Models.Attendee", b =>
                {
                    b.Property<int>("AttendeeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BadgeName");

                    b.Property<string>("ConfirmationNumber");

                    b.Property<int?>("TicketWindowId");

                    b.HasKey("AttendeeId");

                    b.HasIndex("TicketWindowId");

                    b.ToTable("Attendees");
                });

            modelBuilder.Entity("LineCon.Models.TicketWindow", b =>
                {
                    b.Property<int>("TicketWindowId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<TimeSpan>("Time");

                    b.HasKey("TicketWindowId");

                    b.ToTable("TicketWindow");
                });

            modelBuilder.Entity("LineCon.Models.Attendee", b =>
                {
                    b.HasOne("LineCon.Models.TicketWindow", "TicketWindow")
                        .WithMany()
                        .HasForeignKey("TicketWindowId");
                });
#pragma warning restore 612, 618
        }
    }
}
