// <auto-generated />
using System;
using LineCon.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LineCon.Migrations
{
    [DbContext(typeof(LineConContext))]
    [Migration("20190130045308_AttendeeTicket")]
    partial class AttendeeTicket
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LineCon.Models.Attendee", b =>
                {
                    b.Property<Guid>("AttendeeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BadgeName")
                        .IsRequired();

                    b.Property<string>("ConfirmationNumber")
                        .IsRequired();

                    b.HasKey("AttendeeId");

                    b.ToTable("Attendees");
                });

            modelBuilder.Entity("LineCon.Models.AttendeeTicket", b =>
                {
                    b.Property<Guid>("AttendeeTicketId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AttendeeId");

                    b.Property<bool>("Completed");

                    b.Property<Guid>("TicketWindowId");

                    b.HasKey("AttendeeTicketId");

                    b.HasIndex("AttendeeId");

                    b.HasIndex("TicketWindowId");

                    b.ToTable("AttendeeTickets");
                });

            modelBuilder.Entity("LineCon.Models.TicketWindow", b =>
                {
                    b.Property<Guid>("TicketWindowId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AttendeeCapacity");

                    b.Property<TimeSpan>("Length");

                    b.Property<DateTime>("StartTime");

                    b.HasKey("TicketWindowId");

                    b.ToTable("TicketWindows");
                });

            modelBuilder.Entity("LineCon.Models.AttendeeTicket", b =>
                {
                    b.HasOne("LineCon.Models.Attendee", "Attendee")
                        .WithMany()
                        .HasForeignKey("AttendeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LineCon.Models.TicketWindow", "TicketWindow")
                        .WithMany("AttendeeTickets")
                        .HasForeignKey("TicketWindowId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
