// <auto-generated />
using System;
using LineCon.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LineCon.Migrations
{
    [DbContext(typeof(LineConContext))]
    partial class LineConContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LineCon.Models.Attendee", b =>
                {
                    b.Property<Guid>("AttendeeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BadgeName");

                    b.Property<string>("ConfirmationNumber");

                    b.Property<Guid>("TicketWindowId");

                    b.HasKey("AttendeeId");

                    b.HasIndex("TicketWindowId");

                    b.ToTable("Attendees");
                });

            modelBuilder.Entity("LineCon.Models.TicketWindow", b =>
                {
                    b.Property<Guid>("TicketWindowId")
                        .ValueGeneratedOnAdd();

                    b.Property<TimeSpan>("Length");

                    b.Property<DateTime>("StartTime");

                    b.HasKey("TicketWindowId");

                    b.ToTable("TicketWindows");
                });

            modelBuilder.Entity("LineCon.Models.Attendee", b =>
                {
                    b.HasOne("LineCon.Models.TicketWindow", "TicketWindow")
                        .WithMany("Attendees")
                        .HasForeignKey("TicketWindowId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
